### ISSUE TITLE
Dataset Unavailable

### ISSUE THREAD

**Issue by Abel0828** [amrayschwabe/PredictingCovidSpreadMobility#1]
Hi! The paper mentions that the data will be released along with the code. Are they going to be made public any time soon? Thanks in advance!

**Comment by amrayschwabe** [comment]
Hi - thanks for raising this and I‘m sorry I didn‘t specify this in the repo. The covid and mobility data used for this can be found in the data folder of the following repo: https://github.com/jopersson/covid19-mobility

I hope this helps and have a nice day!
